# Code generated by Microsoft (R) AutoRest Code Generator 0.10.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Azure
  #
  # Defines values for AccountType
  #
  module AccountType
    Standard_LRS = "StandardLRS"
    Standard_ZRS = "StandardZRS"
    Standard_GRS = "StandardGRS"
    Standard_RAGRS = "StandardRAGRS"
    Premium_LRS = "PremiumLRS"
  end
end
