# Code generated by Microsoft (R) AutoRest Code Generator 0.10.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Azure
  module Models
    #
    # Model object.
    #
    class CheckNameAvailabilityResponse
      # @return [Boolean] Gets a boolean value that indicates whether the name
      # is available for you to use. If true, the name is available. If
      # false, the name has already been taken or invalid and cannot be used.
      attr_accessor :name_available

      # @return Gets the reason that a storage account name could not be used.
      # The Reason element is only returned if NameAvailable is false.
      # Possible values for this property include: 'AccountNameInvalid',
      # 'AlreadyExists'
      attr_accessor :reason

      # @return [String] Gets an error message explaining the Reason value in
      # more detail.
      attr_accessor :message

      #
      # Validate the object. Throws ArgumentError if validation fails.
      #
      def validate
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(object)
        object.validate
        output_object = {}

        serialized_property = object.name_available
        output_object['nameAvailable'] = serialized_property

        serialized_property = object.reason
        output_object['reason'] = serialized_property

        serialized_property = object.message
        output_object['message'] = serialized_property
        output_object
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [CheckNameAvailabilityResponse] Deserialized object.
      #
      def self.deserialize_object(object)
        return if object.nil?
        output_object = CheckNameAvailabilityResponse.new

        deserialized_property = object['nameAvailable']
        output_object.name_available = deserialized_property

        deserialized_property = object['reason']
        fail ClientRuntime::DeserializationError.new('Error occured in deserializing the enum', nil, nil, nil) if (!deserialized_property.nil? && !deserialized_property.empty? && !Azure::Reason.constants.any? { |enum| enum.to_s == deserialized_property })
        output_object.reason = deserialized_property

        deserialized_property = object['message']
        output_object.message = deserialized_property
        output_object.validate
        output_object
      end
    end
  end
end
