# Code generated by Microsoft (R) AutoRest Code Generator 0.10.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Azure
  #
  # Defines values for KeyName
  #
  module KeyName
    key1 = "Key1"
    key2 = "Key2"
  end
end
