# Code generated by Microsoft (R) AutoRest Code Generator 0.10.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Azure
  #
  # A service client - single point of access to the REST API.
  #
  class StorageManagementClient < ClientRuntimeAzure::AzureServiceClient
    # @return [String] the base URI of the service.
    attr_accessor :base_url

    # @return [String] The Api Version.
    attr_reader :api_version

    # @return [SubscriptionCloudCredentials] Subscription credentials which
    # uniquely identify Microsoft Azure subscription.
    attr_accessor :credentials

    # @return [Integer] The retry timeout for Long Running Operations.
    attr_accessor :long_running_operation_retry_timeout

    # @return [ServiceClient] Subscription credentials which uniquely identify
    # client subscription.
    attr_accessor :credentials

    # @return storage_accounts
    attr_reader :storage_accounts

    #
    # Creates initializes a new instance of the StorageManagementClient class.
    # @param credentials [ClientRuntime::ServiceClientCredentials] credentials to authorize HTTP requests made by the service client.
    # @param base_url [String] the base URI of the service.
    # @param options [Array] filters to be applied to the HTTP requests.
    #
    def initialize(credentials, base_url = nil, options = nil)
      super(credentials, options)
      @base_url = base_url || 'https://management.azure.com'

      fail ArgumentError, 'credentials is nil' if credentials.nil?
      @credentials = credentials

      @storage_accounts = StorageAccounts.new(self)
    end

  end
end
